name: Build DLL Demo with MSBuild

on:
  push:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Configure with CMake (generate Visual Studio project)
      run: cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build with MSBuild
      run: msbuild build/qrcodegen.vcxproj /p:Configuration=Release

    - name: List output
      run: dir build\\Release

    - name: Check DLL existence
      run: |
        if (!(Test-Path build\\Release\\qrcodegen.dll)) {
          throw "DLL not found! Compilation failed or linking skipped."
        }

    - name: Package DLL
      run: |
        mkdir artifacts
        copy build\\Release\\qrcodegen.dll artifacts\\
        powershell Compress-Archive -Path artifacts\\* -DestinationPath qrcodegen_dll.zip

    - name: Upload Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: qrcodegen_dll.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
