name: Build DLL Demo

on:
  push:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Check DLL existence
      run: |
        if (!(Test-Path build\Release\qrcodegen.dll)) {
          throw "DLL not found! Compilation failed or linking skipped."
        }

    - name: Package DLL
      run: |
        mkdir artifacts
        copy build\Release\qrcodegen.dll artifacts\
        powershell Compress-Archive -Path artifacts\* -DestinationPath qrcodegen_dll.zip

    - name: Upload Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: qrcodegen_dll.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
